// Action Types
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const SELECT_ADDRESS = 'SELECT_ADDRESS';
export const BALANCE_REQUESTED = 'BALANCE_REQUESTED';
export const BALANCE_REQUEST_FAILED = 'BALANCE_REQUEST_FAILED';
export const BALANCE_REQUEST_SUCCESS = 'BALANCE_REQUEST_SUCCESS';
export const REFRESH_BALANCE = 'REFRESH_BALANCE';

export const SELECT_CREATOR_ID = 'SELECT_CREATOR_ID';
export const ASSETS_REQUESTED = 'ASSETS_REQUESTED';
export const ASSETS_REQUEST_FAILED = 'ASSETS_REQUEST_FAILED';
export const ASSET_REQUEST_SUCCESS = 'ASSET_REQUEST_SUCCESS';
export const REFRESH_ASSETS = 'REFRESH_ASSETS';