// Action Types
export const SELECT_ADDRESS = 'SELECT_ADDRESS';
export const BALANCE_REQUESTED = 'BALANCE_REQUESTED';
export const BALANCE_REQUEST_FAILED = 'BALANCE_REQUEST_FAILED';
export const BALANCE_REQUEST_SUCCESS = 'BALANCE_REQUEST_SUCCESS';
export const REFRESH_BALANCE = 'REFRESH_BALANCE';
