// Action Types
export const BALANCE_REQUESTED = 'BALANCE_REQUESTED';
export const BALANCE_REQUEST_FAILED = 'BALANCE_REQUEST_FAILED';
export const BALANCE_REQUEST_SUCCESS = 'BALANCE_REQUEST_SUCCESS';
